// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_tokens.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAuthToken = `-- name: CreateAuthToken :one
INSERT INTO auth_tokens (user_id, token_hash, token_type, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token_hash, token_type, expires_at, used_at, created_at
`

type CreateAuthTokenParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	TokenType TokenType `json:"token_type"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) (AuthToken, error) {
	row := q.db.QueryRow(ctx, createAuthToken,
		arg.UserID,
		arg.TokenHash,
		arg.TokenType,
		arg.ExpiresAt,
	)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.TokenType,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAuthToken = `-- name: DeleteAuthToken :exec
DELETE FROM auth_tokens WHERE id = $1
`

func (q *Queries) DeleteAuthToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAuthToken, id)
	return err
}

const deleteExpiredAuthTokens = `-- name: DeleteExpiredAuthTokens :execrows
DELETE FROM auth_tokens WHERE expires_at <= NOW()
`

func (q *Queries) DeleteExpiredAuthTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAuthTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserAuthTokens = `-- name: DeleteUserAuthTokens :exec
DELETE FROM auth_tokens WHERE user_id = $1 AND token_type = $2
`

type DeleteUserAuthTokensParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenType TokenType `json:"token_type"`
}

func (q *Queries) DeleteUserAuthTokens(ctx context.Context, arg DeleteUserAuthTokensParams) error {
	_, err := q.db.Exec(ctx, deleteUserAuthTokens, arg.UserID, arg.TokenType)
	return err
}

const getAuthTokenByHash = `-- name: GetAuthTokenByHash :one
SELECT id, user_id, token_hash, token_type, expires_at, used_at, created_at FROM auth_tokens
WHERE token_hash = $1
  AND token_type = $2
  AND expires_at > NOW()
  AND used_at IS NULL
`

type GetAuthTokenByHashParams struct {
	TokenHash string    `json:"token_hash"`
	TokenType TokenType `json:"token_type"`
}

func (q *Queries) GetAuthTokenByHash(ctx context.Context, arg GetAuthTokenByHashParams) (AuthToken, error) {
	row := q.db.QueryRow(ctx, getAuthTokenByHash, arg.TokenHash, arg.TokenType)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.TokenType,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markAuthTokenUsed = `-- name: MarkAuthTokenUsed :exec
UPDATE auth_tokens
SET used_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkAuthTokenUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAuthTokenUsed, id)
	return err
}
