// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_identities.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOAuthIdentity = `-- name: CreateOAuthIdentity :one
INSERT INTO oauth_identities (user_id, provider, provider_user_id, access_token, refresh_token, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, provider, provider_user_id, access_token, refresh_token, expires_at, created_at, updated_at
`

type CreateOAuthIdentityParams struct {
	UserID         uuid.UUID          `json:"user_id"`
	Provider       OauthProvider      `json:"provider"`
	ProviderUserID string             `json:"provider_user_id"`
	AccessToken    *string            `json:"access_token"`
	RefreshToken   *string            `json:"refresh_token"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateOAuthIdentity(ctx context.Context, arg CreateOAuthIdentityParams) (OauthIdentity, error) {
	row := q.db.QueryRow(ctx, createOAuthIdentity,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
	)
	var i OauthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOAuthIdentity = `-- name: DeleteOAuthIdentity :exec
DELETE FROM oauth_identities WHERE id = $1
`

func (q *Queries) DeleteOAuthIdentity(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOAuthIdentity, id)
	return err
}

const getOAuthIdentitiesByUser = `-- name: GetOAuthIdentitiesByUser :many
SELECT id, user_id, provider, provider_user_id, access_token, refresh_token, expires_at, created_at, updated_at FROM oauth_identities
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetOAuthIdentitiesByUser(ctx context.Context, userID uuid.UUID) ([]OauthIdentity, error) {
	rows, err := q.db.Query(ctx, getOAuthIdentitiesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthIdentity{}
	for rows.Next() {
		var i OauthIdentity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderUserID,
			&i.AccessToken,
			&i.RefreshToken,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOAuthIdentity = `-- name: GetOAuthIdentity :one
SELECT id, user_id, provider, provider_user_id, access_token, refresh_token, expires_at, created_at, updated_at FROM oauth_identities
WHERE provider = $1 AND provider_user_id = $2
`

type GetOAuthIdentityParams struct {
	Provider       OauthProvider `json:"provider"`
	ProviderUserID string        `json:"provider_user_id"`
}

func (q *Queries) GetOAuthIdentity(ctx context.Context, arg GetOAuthIdentityParams) (OauthIdentity, error) {
	row := q.db.QueryRow(ctx, getOAuthIdentity, arg.Provider, arg.ProviderUserID)
	var i OauthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOAuthTokens = `-- name: UpdateOAuthTokens :exec
UPDATE oauth_identities
SET access_token = $2, refresh_token = $3, expires_at = $4, updated_at = NOW()
WHERE id = $1
`

type UpdateOAuthTokensParams struct {
	ID           uuid.UUID          `json:"id"`
	AccessToken  *string            `json:"access_token"`
	RefreshToken *string            `json:"refresh_token"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpdateOAuthTokens(ctx context.Context, arg UpdateOAuthTokensParams) error {
	_, err := q.db.Exec(ctx, updateOAuthTokens,
		arg.ID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
	)
	return err
}
