// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountUsers(ctx context.Context) (int64, error)
	CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) (AuthToken, error)
	CreateOAuthIdentity(ctx context.Context, arg CreateOAuthIdentityParams) (OauthIdentity, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWebhookEvent(ctx context.Context, arg CreateWebhookEventParams) (WebhookEvent, error)
	DeleteAuthToken(ctx context.Context, id uuid.UUID) error
	DeleteExpiredAuthTokens(ctx context.Context) (int64, error)
	DeleteExpiredSessions(ctx context.Context) (int64, error)
	DeleteOAuthIdentity(ctx context.Context, id uuid.UUID) error
	DeleteSession(ctx context.Context, id uuid.UUID) error
	DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteUserAuthTokens(ctx context.Context, arg DeleteUserAuthTokensParams) error
	DeleteUserSessions(ctx context.Context, userID uuid.UUID) error
	GetAuthTokenByHash(ctx context.Context, arg GetAuthTokenByHashParams) (AuthToken, error)
	GetOAuthIdentitiesByUser(ctx context.Context, userID uuid.UUID) ([]OauthIdentity, error)
	GetOAuthIdentity(ctx context.Context, arg GetOAuthIdentityParams) (OauthIdentity, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetWebhookEventByEventID(ctx context.Context, eventID string) (WebhookEvent, error)
	ListUnprocessedWebhookEvents(ctx context.Context, limit int32) ([]WebhookEvent, error)
	ListUserSessions(ctx context.Context, userID uuid.UUID) ([]Session, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	MarkAuthTokenUsed(ctx context.Context, id uuid.UUID) error
	MarkWebhookError(ctx context.Context, arg MarkWebhookErrorParams) error
	MarkWebhookProcessed(ctx context.Context, id uuid.UUID) error
	UpdateOAuthTokens(ctx context.Context, arg UpdateOAuthTokensParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserBilling(ctx context.Context, arg UpdateUserBillingParams) error
	UpdateUserEmailVerified(ctx context.Context, arg UpdateUserEmailVerifiedParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
	UpdateUserTOTP(ctx context.Context, arg UpdateUserTOTPParams) error
}

var _ Querier = (*Queries)(nil)
