// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, name, role)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, name, role, email_verified, totp_secret, totp_enabled, stripe_customer_id, plan, subscription_status, subscription_id, created_at, updated_at
`

type CreateUserParams struct {
	Email        string   `json:"email"`
	PasswordHash *string  `json:"password_hash"`
	Name         string   `json:"name"`
	Role         UserRole `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.EmailVerified,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.StripeCustomerID,
		&i.Plan,
		&i.SubscriptionStatus,
		&i.SubscriptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, role, email_verified, totp_secret, totp_enabled, stripe_customer_id, plan, subscription_status, subscription_id, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.EmailVerified,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.StripeCustomerID,
		&i.Plan,
		&i.SubscriptionStatus,
		&i.SubscriptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, role, email_verified, totp_secret, totp_enabled, stripe_customer_id, plan, subscription_status, subscription_id, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.EmailVerified,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.StripeCustomerID,
		&i.Plan,
		&i.SubscriptionStatus,
		&i.SubscriptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, name, role, email_verified, totp_secret, totp_enabled, stripe_customer_id, plan, subscription_status, subscription_id, created_at, updated_at FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Name,
			&i.Role,
			&i.EmailVerified,
			&i.TotpSecret,
			&i.TotpEnabled,
			&i.StripeCustomerID,
			&i.Plan,
			&i.SubscriptionStatus,
			&i.SubscriptionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, name, role, email_verified, totp_secret, totp_enabled, stripe_customer_id, plan, subscription_status, subscription_id, created_at, updated_at
`

type UpdateUserParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.EmailVerified,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.StripeCustomerID,
		&i.Plan,
		&i.SubscriptionStatus,
		&i.SubscriptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserBilling = `-- name: UpdateUserBilling :exec
UPDATE users
SET stripe_customer_id = $2,
    plan = $3,
    subscription_status = $4,
    subscription_id = $5,
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserBillingParams struct {
	ID                 uuid.UUID          `json:"id"`
	StripeCustomerID   *string            `json:"stripe_customer_id"`
	Plan               string             `json:"plan"`
	SubscriptionStatus SubscriptionStatus `json:"subscription_status"`
	SubscriptionID     *string            `json:"subscription_id"`
}

func (q *Queries) UpdateUserBilling(ctx context.Context, arg UpdateUserBillingParams) error {
	_, err := q.db.Exec(ctx, updateUserBilling,
		arg.ID,
		arg.StripeCustomerID,
		arg.Plan,
		arg.SubscriptionStatus,
		arg.SubscriptionID,
	)
	return err
}

const updateUserEmailVerified = `-- name: UpdateUserEmailVerified :exec
UPDATE users
SET email_verified = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserEmailVerifiedParams struct {
	ID            uuid.UUID `json:"id"`
	EmailVerified bool      `json:"email_verified"`
}

func (q *Queries) UpdateUserEmailVerified(ctx context.Context, arg UpdateUserEmailVerifiedParams) error {
	_, err := q.db.Exec(ctx, updateUserEmailVerified, arg.ID, arg.EmailVerified)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash *string   `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users
SET role = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserRoleParams struct {
	ID   uuid.UUID `json:"id"`
	Role UserRole  `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserRole, arg.ID, arg.Role)
	return err
}

const updateUserTOTP = `-- name: UpdateUserTOTP :exec
UPDATE users
SET totp_secret = $2, totp_enabled = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateUserTOTPParams struct {
	ID          uuid.UUID `json:"id"`
	TotpSecret  *string   `json:"totp_secret"`
	TotpEnabled bool      `json:"totp_enabled"`
}

func (q *Queries) UpdateUserTOTP(ctx context.Context, arg UpdateUserTOTPParams) error {
	_, err := q.db.Exec(ctx, updateUserTOTP, arg.ID, arg.TotpSecret, arg.TotpEnabled)
	return err
}
