// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook_events.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createWebhookEvent = `-- name: CreateWebhookEvent :one
INSERT INTO webhook_events (event_id, event_type, payload)
VALUES ($1, $2, $3)
RETURNING id, event_id, event_type, payload, processed, processed_at, error, created_at
`

type CreateWebhookEventParams struct {
	EventID   string          `json:"event_id"`
	EventType string          `json:"event_type"`
	Payload   json.RawMessage `json:"payload"`
}

func (q *Queries) CreateWebhookEvent(ctx context.Context, arg CreateWebhookEventParams) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, createWebhookEvent, arg.EventID, arg.EventType, arg.Payload)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventType,
		&i.Payload,
		&i.Processed,
		&i.ProcessedAt,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const getWebhookEventByEventID = `-- name: GetWebhookEventByEventID :one
SELECT id, event_id, event_type, payload, processed, processed_at, error, created_at FROM webhook_events WHERE event_id = $1
`

func (q *Queries) GetWebhookEventByEventID(ctx context.Context, eventID string) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, getWebhookEventByEventID, eventID)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventType,
		&i.Payload,
		&i.Processed,
		&i.ProcessedAt,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const listUnprocessedWebhookEvents = `-- name: ListUnprocessedWebhookEvents :many
SELECT id, event_id, event_type, payload, processed, processed_at, error, created_at FROM webhook_events
WHERE NOT processed
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListUnprocessedWebhookEvents(ctx context.Context, limit int32) ([]WebhookEvent, error) {
	rows, err := q.db.Query(ctx, listUnprocessedWebhookEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEvent{}
	for rows.Next() {
		var i WebhookEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EventType,
			&i.Payload,
			&i.Processed,
			&i.ProcessedAt,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookError = `-- name: MarkWebhookError :exec
UPDATE webhook_events
SET error = $2
WHERE id = $1
`

type MarkWebhookErrorParams struct {
	ID    uuid.UUID `json:"id"`
	Error *string   `json:"error"`
}

func (q *Queries) MarkWebhookError(ctx context.Context, arg MarkWebhookErrorParams) error {
	_, err := q.db.Exec(ctx, markWebhookError, arg.ID, arg.Error)
	return err
}

const markWebhookProcessed = `-- name: MarkWebhookProcessed :exec
UPDATE webhook_events
SET processed = TRUE, processed_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkWebhookProcessed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markWebhookProcessed, id)
	return err
}
